# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Language.create(short: "ara", full: "Arabic", enabled: false) 
Language.create(short: "aze", full: "Azerbauijani", enabled: false) 
Language.create(short: "bul", full: "Bulgarian", enabled: false) 
Language.create(short: "cat", full: "Catalan", enabled: false) 
Language.create(short: "ces", full: "Czech", enabled: false) 
Language.create(short: "chi_sim", full: "Simplified Chinese", enabled: false) 
Language.create(short: "chi_tra", full: "Traditional Chinese", enabled: false) 
Language.create(short: "chr", full: "Cherokee", enabled: false) 
Language.create(short: "dan", full: "Danish", enabled: false) 
Language.create(short: "dan-frak", full: "Danish (Fraktur)", enabled: false) 
Language.create(short: "deu", full: "German", enabled: false) 
Language.create(short: "ell", full: "Greek", enabled: false) 
Language.create(short: "eng", full: "English", enabled: true) 
Language.create(short: "enm", full: "Old English", enabled: false) 
Language.create(short: "epo", full: "Esperanto", enabled: false) 
Language.create(short: "est", full: "Estonian", enabled: false) 
Language.create(short: "fin", full: "Finnish", enabled: false) 
Language.create(short: "fra", full: "French", enabled: false) 
Language.create(short: "frm", full: "Old French", enabled: false) 
Language.create(short: "glg", full: "Galician", enabled: false) 
Language.create(short: "heb", full: "Hebrew", enabled: false) 
Language.create(short: "hin", full: "Hindi", enabled: false) 
Language.create(short: "hrv", full: "Croation", enabled: false) 
Language.create(short: "hun", full: "Hungarian", enabled: false) 
Language.create(short: "ind", full: "Indonesian", enabled: false) 
Language.create(short: "ita", full: "Italian", enabled: false) 
Language.create(short: "jpn", full: "Japanese", enabled: false) 
Language.create(short: "kor", full: "Korean", enabled: false) 
Language.create(short: "lav", full: "Latvian", enabled: false) 
Language.create(short: "lit", full: "Lithuanian", enabled: false) 
Language.create(short: "nld", full: "Dutch", enabled: false) 
Language.create(short: "nor", full: "Norwegian", enabled: false) 
Language.create(short: "pol", full: "Polish", enabled: false) 
Language.create(short: "por", full: "Portuguese", enabled: false) 
Language.create(short: "ron", full: "Romanian", enabled: false) 
Language.create(short: "rus", full: "Russian", enabled: false) 
Language.create(short: "slk", full: "Slovakian", enabled: false) 
Language.create(short: "slv", full: "Slovenian", enabled: false) 
Language.create(short: "sqi", full: "Albanian", enabled: false) 
Language.create(short: "spa", full: "Spanish", enabled: true) 
Language.create(short: "srp", full: "Serbian", enabled: false) 
Language.create(short: "swe", full: "Swedish", enabled: true) 
Language.create(short: "tam", full: "Tamil", enabled: false) 
Language.create(short: "tel", full: "Telugu", enabled: false) 
Language.create(short: "tgl", full: "Tagalog", enabled: false) 
Language.create(short: "tha", full: "Thai", enabled: false) 
Language.create(short: "tur", full: "Turkish", enabled: false) 
Language.create(short: "ukr", full: "Ukrainian", enabled: false) 
Language.create(short: "vie", full: "(Vietnamese)", enabled: false) 



Template.create(user_id: 1, group_id: "", style_id: "", type_id: "", name: "Test Template", description: "Test", path: "", url: "", filename: "")
Section.create(template_id: 1,name: "one",yOrigin: 10,xOrigin: 15,width: 1242, height: 67)
Section.create(template_id: 1,name: "two",yOrigin: 857,xOrigin: 512,width: 330, height: 52)